
compute_environment: LOCAL_MACHINE
debug: false
# deepspeed_config:
#   # multinode_launcher: standard
#   gradient_accumulation_steps: 2
#   gradient_clipping: 1.0
#   offload_optimizer_device: cpu
#   offload_param_device: cpu
#   zero3_init_flag: True
#   zero_stage: 3
  # main_process_port: 34000
distributed_type: MULTI_GPU 
downcast_bf16: 'no'
main_process_port: 34000
enable_cpu_affinity: false
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false